#define IDR_REMOTE 101
#define IDR_BUMTON_PRESSED 102
#define IDR_BUMTON_WIDE_PRESSED 103
#define IDR_BUMTON_PRESSED_SAND 104
#define IDR_BUMTON_PRESSED_GAY 105
#define IDR_BUMTON_PRESSED_ROCK 106
#define IDR_BUMTON_PRESSED_STOP 201